import os

import pytest

from datapipes import DatapipeType
from datapipes import initialize_datapipe
from tasks import RunPythonCode


@pytest.fixture
def datapipe():
    datapipe = initialize_datapipe(datapipe=DatapipeType.MEMORY)
    return datapipe


def test_execute(datapipe):
    data = {
        "data": [
            {
                "date": 1596240000000,
                "total_sleep_time": 461.5,
                "awake_duration": 18.5,
                "light_sleep_duration": 242.5,
                "rem_sleep_duration": 118.0,
                "deep_sleep_duration": 101.0,
                "sleep_onset_latency": 4.0,
                "midpoint_time_of_sleep": 240.0,
                "sleep_efficiency": 96,
                "average_heart_rate": 70.97,
                "minimum_heart_rate": 63,
                "rmssd": 33,
                "average_breathing_rate": 17.38,
                "temperature_variation": 0.56,
            },
            {
                "date": 1596326400000,
                "total_sleep_time": 493.5,
                "awake_duration": 56.5,
                "light_sleep_duration": 254.0,
                "rem_sleep_duration": 142.5,
                "deep_sleep_duration": 97.0,
                "sleep_onset_latency": 19.5,
                "midpoint_time_of_sleep": 276.0,
                "sleep_efficiency": 90,
                "average_heart_rate": 68.4,
                "minimum_heart_rate": 59,
                "rmssd": 33,
                "average_breathing_rate": 16.88,
                "temperature_variation": 0.23,
            },
            {
                "date": 1596412800000,
                "total_sleep_time": 506.5,
                "awake_duration": 59.5,
                "light_sleep_duration": 328.0,
                "rem_sleep_duration": 127.0,
                "deep_sleep_duration": 51.5,
                "sleep_onset_latency": 18.0,
                "midpoint_time_of_sleep": 297.0,
                "sleep_efficiency": 89,
                "average_heart_rate": 70.75,
                "minimum_heart_rate": 62,
                "rmssd": 23,
                "average_breathing_rate": 16.38,
                "temperature_variation": -0.01,
            },
            {
                "date": 1596499200000,
                "total_sleep_time": 423.5,
                "awake_duration": 22.5,
                "light_sleep_duration": 240.5,
                "rem_sleep_duration": 106.0,
                "deep_sleep_duration": 77.0,
                "sleep_onset_latency": 13.0,
                "midpoint_time_of_sleep": 226.5,
                "sleep_efficiency": 95,
                "average_heart_rate": 69.57,
                "minimum_heart_rate": 62,
                "rmssd": 30,
                "average_breathing_rate": 17.25,
                "temperature_variation": 0.22,
            },
            {
                "date": 1596585600000,
                "total_sleep_time": 456.5,
                "awake_duration": 33.5,
                "light_sleep_duration": 259.5,
                "rem_sleep_duration": 96.0,
                "deep_sleep_duration": 101.0,
                "sleep_onset_latency": 11.5,
                "midpoint_time_of_sleep": 244.5,
                "sleep_efficiency": 93,
                "average_heart_rate": 64.31,
                "minimum_heart_rate": 58,
                "rmssd": 47,
                "average_breathing_rate": 17.38,
                "temperature_variation": 0.11,
            },
            {
                "date": 1596758400000,
                "total_sleep_time": 425.0,
                "awake_duration": 47.0,
                "light_sleep_duration": 218.5,
                "rem_sleep_duration": 102.5,
                "deep_sleep_duration": 104.0,
                "sleep_onset_latency": 21.5,
                "midpoint_time_of_sleep": 228.5,
                "sleep_efficiency": 90,
                "average_heart_rate": 66.4,
                "minimum_heart_rate": 58,
                "rmssd": 32,
                "average_breathing_rate": 16.62,
                "temperature_variation": 0.01,
            },
            {
                "date": 1596844800000,
                "total_sleep_time": 410.5,
                "awake_duration": 68.5,
                "light_sleep_duration": 187.0,
                "rem_sleep_duration": 118.5,
                "deep_sleep_duration": 105.0,
                "sleep_onset_latency": 17.5,
                "midpoint_time_of_sleep": 230.5,
                "sleep_efficiency": 86,
                "average_heart_rate": 63.61,
                "minimum_heart_rate": 55,
                "rmssd": 39,
                "average_breathing_rate": 16.62,
                "temperature_variation": -0.05,
            },
            {
                "date": 1596931200000,
                "total_sleep_time": 459.0,
                "awake_duration": 45.0,
                "light_sleep_duration": 207.0,
                "rem_sleep_duration": 103.0,
                "deep_sleep_duration": 149.0,
                "sleep_onset_latency": 6.5,
                "midpoint_time_of_sleep": 243.5,
                "sleep_efficiency": 91,
                "average_heart_rate": 61.97,
                "minimum_heart_rate": 56,
                "rmssd": 60,
                "average_breathing_rate": 16.75,
                "temperature_variation": 0.05,
            },
            {
                "date": 1597017600000,
                "total_sleep_time": 415.5,
                "awake_duration": 25.5,
                "light_sleep_duration": 195.0,
                "rem_sleep_duration": 112.0,
                "deep_sleep_duration": 108.5,
                "sleep_onset_latency": 10.0,
                "midpoint_time_of_sleep": 219.5,
                "sleep_efficiency": 94,
                "average_heart_rate": 65.19,
                "minimum_heart_rate": 58,
                "rmssd": 31,
                "average_breathing_rate": 16.62,
                "temperature_variation": 0.01,
            },
            {
                "date": 1597104000000,
                "total_sleep_time": 424.5,
                "awake_duration": 33.5,
                "light_sleep_duration": 185.0,
                "rem_sleep_duration": 118.0,
                "deep_sleep_duration": 121.5,
                "sleep_onset_latency": 14.0,
                "midpoint_time_of_sleep": 227.5,
                "sleep_efficiency": 93,
                "average_heart_rate": 64.54,
                "minimum_heart_rate": 58,
                "rmssd": 34,
                "average_breathing_rate": 16.25,
                "temperature_variation": -0.12,
            },
            {
                "date": 1597190400000,
                "total_sleep_time": 428.0,
                "awake_duration": 34.0,
                "light_sleep_duration": 230.0,
                "rem_sleep_duration": 101.5,
                "deep_sleep_duration": 96.5,
                "sleep_onset_latency": 4.0,
                "midpoint_time_of_sleep": 221.0,
                "sleep_efficiency": 93,
                "average_heart_rate": 66.22,
                "minimum_heart_rate": 59,
                "rmssd": 42,
                "average_breathing_rate": 16.62,
                "temperature_variation": -0.05,
            },
            {
                "date": 1597276800000,
                "total_sleep_time": 382.5,
                "awake_duration": 19.5,
                "light_sleep_duration": 169.0,
                "rem_sleep_duration": 94.0,
                "deep_sleep_duration": 119.5,
                "sleep_onset_latency": 10.0,
                "midpoint_time_of_sleep": 198.5,
                "sleep_efficiency": 95,
                "average_heart_rate": 66.52,
                "minimum_heart_rate": 59,
                "rmssd": 35,
                "average_breathing_rate": 16.38,
                "temperature_variation": 0.15,
            },
            {
                "date": 1597363200000,
                "total_sleep_time": 496.5,
                "awake_duration": 28.5,
                "light_sleep_duration": 280.5,
                "rem_sleep_duration": 116.5,
                "deep_sleep_duration": 99.5,
                "sleep_onset_latency": 13.0,
                "midpoint_time_of_sleep": 262.0,
                "sleep_efficiency": 95,
                "average_heart_rate": 65.56,
                "minimum_heart_rate": 56,
                "rmssd": 34,
                "average_breathing_rate": 15.88,
                "temperature_variation": -0.04,
            },
            {
                "date": 1597622400000,
                "total_sleep_time": 446.0,
                "awake_duration": 75.0,
                "light_sleep_duration": 245.5,
                "rem_sleep_duration": 76.5,
                "deep_sleep_duration": 124.0,
                "sleep_onset_latency": 22.0,
                "midpoint_time_of_sleep": 244.5,
                "sleep_efficiency": 86,
                "average_heart_rate": 63.76,
                "minimum_heart_rate": 56,
                "rmssd": 45,
                "average_breathing_rate": 16.62,
                "temperature_variation": 0.06,
            },
            {
                "date": 1597708800000,
                "total_sleep_time": 452.5,
                "awake_duration": 61.5,
                "light_sleep_duration": 250.5,
                "rem_sleep_duration": 106.5,
                "deep_sleep_duration": 95.5,
                "sleep_onset_latency": 15.5,
                "midpoint_time_of_sleep": 243.5,
                "sleep_efficiency": 88,
                "average_heart_rate": 63.09,
                "minimum_heart_rate": 55,
                "rmssd": 43,
                "average_breathing_rate": 16.25,
                "temperature_variation": -0.27,
            },
            {
                "date": 1597881600000,
                "total_sleep_time": 458.5,
                "awake_duration": 66.5,
                "light_sleep_duration": 261.0,
                "rem_sleep_duration": 109.0,
                "deep_sleep_duration": 88.5,
                "sleep_onset_latency": 18.5,
                "midpoint_time_of_sleep": 254.0,
                "sleep_efficiency": 87,
                "average_heart_rate": 66.6,
                "minimum_heart_rate": 60,
                "rmssd": 41,
                "average_breathing_rate": 16.12,
                "temperature_variation": -0.1,
            },
            {
                "date": 1597968000000,
                "total_sleep_time": 305.0,
                "awake_duration": 67.0,
                "light_sleep_duration": 194.5,
                "rem_sleep_duration": 55.5,
                "deep_sleep_duration": 55.0,
                "sleep_onset_latency": 20.5,
                "midpoint_time_of_sleep": 203.5,
                "sleep_efficiency": 82,
                "average_heart_rate": 64.71,
                "minimum_heart_rate": 57,
                "rmssd": 50,
                "average_breathing_rate": 15.88,
                "temperature_variation": 0.07,
            },
            {
                "date": 1598140800000,
                "total_sleep_time": 358.0,
                "awake_duration": 23.0,
                "light_sleep_duration": 210.5,
                "rem_sleep_duration": 53.0,
                "deep_sleep_duration": 94.5,
                "sleep_onset_latency": 5.5,
                "midpoint_time_of_sleep": 185.5,
                "sleep_efficiency": 94,
                "average_heart_rate": 66.77,
                "minimum_heart_rate": 59,
                "rmssd": 36,
                "average_breathing_rate": 15.75,
                "temperature_variation": -0.31,
            },
            {
                "date": 1598227200000,
                "total_sleep_time": 537.5,
                "awake_duration": 36.5,
                "light_sleep_duration": 232.0,
                "rem_sleep_duration": 176.5,
                "deep_sleep_duration": 129.0,
                "sleep_onset_latency": 9.0,
                "midpoint_time_of_sleep": 280.5,
                "sleep_efficiency": 94,
                "average_heart_rate": 64.42,
                "minimum_heart_rate": 57,
                "rmssd": 44,
                "average_breathing_rate": 16.25,
                "temperature_variation": -0.02,
            },
            {
                "date": 1598313600000,
                "total_sleep_time": 469.0,
                "awake_duration": 30.0,
                "light_sleep_duration": 272.0,
                "rem_sleep_duration": 72.0,
                "deep_sleep_duration": 125.0,
                "sleep_onset_latency": 13.0,
                "midpoint_time_of_sleep": 250.0,
                "sleep_efficiency": 94,
                "average_heart_rate": 63.14,
                "minimum_heart_rate": 58,
                "rmssd": 45,
                "average_breathing_rate": 16.5,
                "temperature_variation": 0.16,
            },
            {
                "date": 1598400000000,
                "total_sleep_time": 561.0,
                "awake_duration": 48.0,
                "light_sleep_duration": 285.5,
                "rem_sleep_duration": 164.5,
                "deep_sleep_duration": 111.0,
                "sleep_onset_latency": 8.5,
                "midpoint_time_of_sleep": 311.5,
                "sleep_efficiency": 92,
                "average_heart_rate": 67.03,
                "minimum_heart_rate": 60,
                "rmssd": 31,
                "average_breathing_rate": 16.12,
                "temperature_variation": 0.32,
            },
            {
                "date": 1598486400000,
                "total_sleep_time": 438.5,
                "awake_duration": 72.5,
                "light_sleep_duration": 257.5,
                "rem_sleep_duration": 90.5,
                "deep_sleep_duration": 90.5,
                "sleep_onset_latency": 27.5,
                "midpoint_time_of_sleep": 247.5,
                "sleep_efficiency": 86,
                "average_heart_rate": 68.89,
                "minimum_heart_rate": 60,
                "rmssd": 33,
                "average_breathing_rate": 16.25,
                "temperature_variation": 0.2,
            },
            {
                "date": 1598572800000,
                "total_sleep_time": 580.5,
                "awake_duration": 24.5,
                "light_sleep_duration": 300.0,
                "rem_sleep_duration": 208.0,
                "deep_sleep_duration": 72.5,
                "sleep_onset_latency": 0.5,
                "midpoint_time_of_sleep": 302.0,
                "sleep_efficiency": 96,
                "average_heart_rate": 69.93,
                "minimum_heart_rate": 63,
                "rmssd": 24,
                "average_breathing_rate": 16.25,
                "temperature_variation": 0.13,
            },
            {
                "date": 1598659200000,
                "total_sleep_time": 410.5,
                "awake_duration": 41.5,
                "light_sleep_duration": 231.0,
                "rem_sleep_duration": 102.5,
                "deep_sleep_duration": 77.0,
                "sleep_onset_latency": 9.5,
                "midpoint_time_of_sleep": 219.0,
                "sleep_efficiency": 91,
                "average_heart_rate": 70.65,
                "minimum_heart_rate": 67,
                "rmssd": 26,
                "average_breathing_rate": 16.62,
                "temperature_variation": 0.32,
            },
            {
                "date": 1598745600000,
                "total_sleep_time": 358.0,
                "awake_duration": 40.0,
                "light_sleep_duration": 163.5,
                "rem_sleep_duration": 64.0,
                "deep_sleep_duration": 130.5,
                "sleep_onset_latency": 9.0,
                "midpoint_time_of_sleep": 196.5,
                "sleep_efficiency": 90,
                "average_heart_rate": 68.51,
                "minimum_heart_rate": 62,
                "rmssd": 28,
                "average_breathing_rate": 16.12,
                "temperature_variation": 0.35,
            },
            {
                "date": 1598832000000,
                "total_sleep_time": 493.0,
                "awake_duration": 52.0,
                "light_sleep_duration": 223.0,
                "rem_sleep_duration": 142.5,
                "deep_sleep_duration": 127.5,
                "sleep_onset_latency": 7.0,
                "midpoint_time_of_sleep": 254.5,
                "sleep_efficiency": 90,
                "average_heart_rate": 69.49,
                "minimum_heart_rate": 61,
                "rmssd": 31,
                "average_breathing_rate": 16.38,
                "temperature_variation": 0.36,
            },
        ],
        "description": ",".join(
            [
                "returns a json array of json objects which contains the following keys:",
                "date (in milliseconds) epoch format",
                "total_sleep_time (in minutes) is Total amount of sleep (a.k.a. sleep duration) registered during the sleep period.",
                "awake_duration (in minutes) is the total amount of awake time registered during the sleep period.",
                "light_sleep_duration (in minutes) is the total amount of light (N1 or N2) sleep registered during the sleep period.",
                "rem_sleep_duration (in minutes) is the total amount of REM sleep registered during the sleep period.",
                "deep_sleep_duration (in minutes) is the total amount of deep (N3) sleep registered during the sleep period.",
                (
                    "sleep_onset_latency (in minutes) is detected latency from bedtime_start to the beginning of the first"
                    "five minutes of persistent sleep."
                ),
                (
                    "midpoint_time_of_sleep (in minutes) is the time from the start of sleep to the midpoint of sleep."
                    "The midpoint ignores awake periods."
                ),
                "sleep_efficiency is the percentage of the sleep period spent asleep (100% * sleep duration / time in bed).",
                "average_heart_rate is the average heart rate registered during the sleep period.",
                "minimum_heart_rate is the lowest heart rate (5 minutes sliding average) registered during the sleep period.",
                "rmssd is the average Root Mean Square of Successive Differences (RMSSD) registered during the sleep period.",
                "average_breathing_rate is the average breathing rate registered during the sleep period.",
                "temperature_variation is the skin temperature deviation from the long-term temperature average.",
            ]
        ),
    }
    run_python_code_task = RunPythonCode()
    result = run_python_code_task._execute(
        [
            "plot total sleep data and fit the regression line of the sleep",
            data,
        ]
    )
    assert os.path.exists(result.split("address:")[-1])
